import { cookies } from "next/headers";
import { createServerClient } from "@nimia/db";
import { InvoicesList, type InvoiceRow } from "./InvoicesList";

export const metadata = { title: "Invoices" };

// Real implementation (10 Agustus 2026) — replaces the ComingSoonState
// placeholder. Reads across ALL clients, same "safe because RLS only
// allows is_admin() to see every row" convention as every other admin
// list page (see Overview's own comment). The PDF itself is generated by
// the existing GET /api/orders/[id]/receipt route
// (packages/db/migrations/0024_order_receipts.sql), same one
// OrderDetailPanel.tsx's per-order "Download Receipt" button already
// linked to.
export default async function InvoicesPage() {
  const supabase = createServerClient(await cookies());

  const { data } = await supabase
    .from("orders")
    .select(
      "id, full_name, company_name, final_price_usd, payment_verified_at, payment_network, payment_token, created_at, services(name), clients(company_name), order_receipts(receipt_number, created_at)",
    )
    .eq("status", "paid")
    .order("payment_verified_at", { ascending: false });

  const invoices: InvoiceRow[] = (data ?? []).map((o: any) => {
    const service = Array.isArray(o.services) ? o.services[0] : o.services;
    const client = Array.isArray(o.clients) ? o.clients[0] : o.clients;
    const receiptRow = Array.isArray(o.order_receipts) ? o.order_receipts[0] : o.order_receipts;
    return {
      orderId: o.id,
      clientLabel: client?.company_name || o.company_name || o.full_name,
      serviceName: service?.name ?? "Custom Project",
      amountUsd: Number(o.final_price_usd ?? 0),
      verifiedAt: o.payment_verified_at,
      createdAt: o.created_at,
      network: o.payment_network,
      token: o.payment_token,
      receiptNumber: receiptRow?.receipt_number ?? null,
    };
  });

  const totalRevenue = invoices.reduce((sum, invoice) => sum + invoice.amountUsd, 0);
  const now = new Date();
  const thisMonthRevenue = invoices
    .filter((invoice) => {
      if (!invoice.verifiedAt) return false;
      const verified = new Date(invoice.verifiedAt);
      return verified.getMonth() === now.getMonth() && verified.getFullYear() === now.getFullYear();
    })
    .reduce((sum, invoice) => sum + invoice.amountUsd, 0);

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Invoices</h1>
        <p className="mt-1 text-sm text-white/45">
          Every verified payment across all clients, with its downloadable PDF receipt.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-3">
        <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-4">
          <p className="text-xs font-medium text-white/45">Total Revenue</p>
          <p className="mt-1 text-xl font-bold text-white">${totalRevenue.toLocaleString("en-US")}</p>
        </div>
        <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-4">
          <p className="text-xs font-medium text-white/45">This Month</p>
          <p className="mt-1 text-xl font-bold text-emerald-300">${thisMonthRevenue.toLocaleString("en-US")}</p>
        </div>
        <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-4">
          <p className="text-xs font-medium text-white/45">Invoices</p>
          <p className="mt-1 text-xl font-bold text-white">{invoices.length}</p>
        </div>
      </div>

      <InvoicesList invoices={invoices} />
    </div>
  );
}
