import { cookies } from "next/headers";
import { createServerClient } from "@nimia/db";
import { InvoicesList, type InvoiceRow } from "./InvoicesList";

export const metadata = { title: "Invoices" };

// Real implementation (10 Agustus 2026) — replaces the "Coming in Phase 5"
// placeholder. Every row is an order this client has actually paid for
// (status='paid'); the PDF is generated by the existing
// GET /api/orders/[id]/receipt route (packages/db/migrations/
// 0024_order_receipts.sql -> get_or_create_order_receipt) — same endpoint
// PaymentPanel.tsx's own per-order "Download Receipt" button already used,
// this page just gives every one of them a dedicated, searchable home
// instead of only being reachable from inside an order's payment tab.
export default async function InvoicesPage() {
  const supabase = createServerClient(await cookies());
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const { data: client } = await supabase
    .from("clients")
    .select("id")
    .eq("user_id", user!.id)
    .single();

  let invoices: InvoiceRow[] = [];

  if (client) {
    const { data } = await supabase
      .from("orders")
      .select(
        "id, final_price_usd, payment_verified_at, payment_network, payment_token, created_at, services(name), order_receipts(receipt_number, created_at)",
      )
      .eq("client_id", client.id)
      .eq("status", "paid")
      .order("payment_verified_at", { ascending: false });

    invoices = (data ?? []).map((o: any) => {
      // Defensive normalization — PostgREST embeds a to-one FK as a plain
      // object, but without generated types (Database is still `any`, see
      // packages/db/src/types.ts) that shape isn't guaranteed at compile
      // time. Same pattern as every other order query in this app.
      const service = Array.isArray(o.services) ? o.services[0] : o.services;
      const receiptRow = Array.isArray(o.order_receipts) ? o.order_receipts[0] : o.order_receipts;
      return {
        orderId: o.id,
        serviceName: service?.name ?? "Custom Project",
        amountUsd: Number(o.final_price_usd ?? 0),
        verifiedAt: o.payment_verified_at,
        createdAt: o.created_at,
        network: o.payment_network,
        token: o.payment_token,
        // Null until either the auto-create-on-paid trigger has run or
        // someone has actually clicked "PDF" once (get_or_create_order_receipt
        // self-heals on first access) — InvoicesList shows a
        // "Generating on download" chip instead of blocking the row on it.
        receiptNumber: receiptRow?.receipt_number ?? null,
      };
    });
  }

  const totalPaid = invoices.reduce((sum, invoice) => sum + invoice.amountUsd, 0);

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold">Invoices</h1>
        <p className="mt-1 text-[var(--nimia-muted)]">
          Every payment Nimia Studio has verified for you, with a downloadable PDF receipt for each.
        </p>
      </div>

      {invoices.length > 0 ? (
        <div className="grid grid-cols-2 gap-4 sm:max-w-md">
          <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-4">
            <p className="text-xs font-medium text-white/45">Total Paid</p>
            <p className="mt-1 text-xl font-bold text-white">${totalPaid.toLocaleString("en-US")}</p>
          </div>
          <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-4">
            <p className="text-xs font-medium text-white/45">Invoices</p>
            <p className="mt-1 text-xl font-bold text-white">{invoices.length}</p>
          </div>
        </div>
      ) : null}

      <InvoicesList invoices={invoices} />
    </div>
  );
}
